#!/bin/bash
set -e

# Tubo — Zero-install sender/receiver
# Uses only curl + openssl. No binaries, no root, no disk writes until the output file.
#
# Receive:  curl -sL https://endlessite.com/run | bash -s receive <token> [output_file]
# Send:     curl -sL https://endlessite.com/run | bash -s send <file> <token>

COMMAND=$1

# --- Shared: parse token and derive AES key/IV ---

parse_token() {
    local TOKEN=$1
    ID=$(echo "$TOKEN" | cut -d'-' -f1)
    PWD_TOK=$(echo "$TOKEN" | cut -d'-' -f2)
    KEY=$(echo "$TOKEN" | cut -d'-' -f3-)

    if [ -z "$ID" ] || [ -z "$PWD_TOK" ] || [ -z "$KEY" ]; then
        echo "Error: Invalid token format. Expected: ID-PASSWORD-KEY" >&2
        exit 1
    fi

    # Server URL (override with TUBO_SERVER env var for self-hosting)
    SERVER=${TUBO_SERVER:-https://tubo.endlessite.com}
    SERVER=$(echo "$SERVER" | sed 's|wss://|https://|' | sed 's|ws://|http://|')
    if ! echo "$SERVER" | grep -qE '^https?://'; then
        SERVER="http://$SERVER"
    fi

    # Derive AES-256-CTR Key and IV from E2EE key using SHA-512
    # Identical to the Go CLI: SHA-512(key) → first 32 bytes = AES Key, next 16 = IV
    HASH=$(printf "%s" "$KEY" | openssl dgst -sha512 | sed 's/^.* //')
    AES_KEY=${HASH:0:64}
    AES_IV=${HASH:64:32}
}

# --- Receive ---

do_receive() {
    local TOKEN=$1
    local OUTFILE=$2

    parse_token "$TOKEN"

    # If no output file specified, auto-detect from Content-Disposition header
    if [ -z "$OUTFILE" ]; then
        HEADER_FILE=$(mktemp)
        TEMP_FILE=$(mktemp)

        echo "Downloading and decrypting..." >&2
        curl -s --fail -u "tubo:$PWD_TOK" -D "$HEADER_FILE" "$SERVER/$ID" \
            | openssl enc -d -aes-256-ctr -K "$AES_KEY" -iv "$AES_IV" > "$TEMP_FILE"

        OUTFILE=$(sed -n 's/.*filename="\([^"]*\)".*/\1/p' "$HEADER_FILE" | tr -d '\r')
        rm -f "$HEADER_FILE"

        if [ -z "$OUTFILE" ]; then
            OUTFILE="download.dat"
        fi

        mv "$TEMP_FILE" "./$OUTFILE"
    else
        echo "Downloading and decrypting to: $OUTFILE" >&2
        curl -s --fail -u "tubo:$PWD_TOK" "$SERVER/$ID" \
            | openssl enc -d -aes-256-ctr -K "$AES_KEY" -iv "$AES_IV" > "$OUTFILE"
    fi

    echo "Done! File saved to ./$OUTFILE" >&2
}

# --- Send ---

do_send() {
    local FILE=$1
    local TOKEN=$2

    if [ ! -f "$FILE" ]; then
        echo "Error: File not found: $FILE" >&2
        exit 1
    fi

    parse_token "$TOKEN"

    local FILENAME
    FILENAME=$(basename "$FILE")

    echo "Encrypting and uploading: $FILENAME" >&2
    echo "End-to-End Encryption: ENABLED (AES-256-CTR)" >&2

    # Encrypt and stream via HTTP POST to the relay server
    cat "$FILE" \
        | openssl enc -e -aes-256-ctr -K "$AES_KEY" -iv "$AES_IV" \
        | curl -s --fail -T - -u "tubo:$PWD_TOK" "$SERVER/$ID/$FILENAME"

    echo "Transfer complete." >&2
}

# --- Main ---

case "$COMMAND" in
    receive)
        if [ -z "$2" ]; then
            echo "Usage:" >&2
            echo "  bash run.sh receive <token> [output_file]" >&2
            echo "  Token is generated by 'tubo send' on the sender machine." >&2
            exit 1
        fi
        do_receive "$2" "$3"
        ;;
    send)
        if [ -z "$2" ] || [ -z "$3" ]; then
            echo "Usage:" >&2
            echo "  bash run.sh send <file> <token>" >&2
            echo "  Token is generated by 'tubo receive' on the receiver machine." >&2
            exit 1
        fi
        do_send "$2" "$3"
        ;;
    *)
        echo "Tubo — Transfer files without root, without hassle." >&2
        echo "" >&2
        echo "  Receive:  bash run.sh receive <token> [output_file]" >&2
        echo "  Send:     bash run.sh send <file> <token>" >&2
        echo "" >&2
        echo "All transfers are end-to-end encrypted. Always." >&2
        exit 1
        ;;
esac
